### ISSUE TITLE
I ran across a few issues while getting this working, wanted to share them.

### ISSUE THREAD

**Issue by MostHated** [tom-a-horrocks/qt-python-mvc#2]
Hey there,
    I wanted to check this out, but out of the box it had some issues. It feels like you were perhaps in the middle of refactoring but forgot to push a commit or something?

I had to move a lot of things around in order to get it to actually attempt to get the example working due to relative import issues, so I moved the model and controller into their own folders and put main at the top level (I am not that great at python application design/structure, nor do I really know 'best practices', I just know what works and what doesn't for me).

<details open>
<summary>Wrong method signature</summary>

In the Binder() class, two_way: has a signature asking for:

```python
def two_way(self, element1, element2, initial_value=None):
```
but then in the View() class, bind_to_model: was attempting to call it, passing in:

```python
b.two_way(elements=(self.line_edit.text, MainModel.edit_text), initial_value='Enter text here...')
```
I wasn't sure exactly which was the your intention of going, but I changed it to:
```python
b.two_way(element1=self.line_edit.text, element2=MainModel.edit_text, initial_value='Enter text here...')
```

I believe that was the biggest thing, after fixing imports and such, I was able to get it running.
</details>

All in all, I am not too familiar with MVC in general, but I think this project is quite neat, and I want to study it a bit and see if I can mimick some of the techniques. :+1:

**Comment by tom-a-horrocks** [comment]
Thanks for this! I've been updating the library as I use it, but the
documentation hasn't kept pace. I'll take a look at this soon 😀.

**Comment by tom-a-horrocks** [comment]
Updated example and readme.
