### ISSUE TITLE
'builtin_function_or_method' object has no attribute '__get__'

### ISSUE THREAD

**Issue by tinhtranbk** [tom-a-horrocks/qt-python-mvc#3]
I got this error: 

   w_getter, w_setter, w_sig = cls._inflate(widget_getter_descriptor,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "binding.py", line 71, in _inflate
    getter_descriptor.__get__(widget),
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute '__get__'. Did you mean: '__ge__'?

if I changed it to __ge__ as recommended, I got another error:

 File "binding.py", line 106, in _bind
    w_setter(initial_value)
TypeError: 'NotImplementedType' object is not callable

I used PyQt6 and Python 3.10

Thank you for your help!

**Comment by tom-a-horrocks** [comment]
I have an idea but I can't say for sure without seeing your code. Please let me know if the following works, and if it doesn't you'll need to provide a bit more code.

Can you please check that in your binding statement (i.e. `one_way` or `two_way`) you refer to your model's property through its class and not through the model object itself? For example:
```
model = MyModel()
b = Binder(model)

# This is correct
b.one_way(source=MainModel.label_text,  # note: MainModel
          sink=self.label.text,
          initial_value='Enter text here...')

# This is incorrect
b.one_way(source=model.label_text,  # note: model
          sink=self.label.text,
          initial_value='Enter text here...')
```

**Comment by tinhtranbk** [comment]
Hi Tom,

The error arose from :
b.two_way(self.line_edit.text,
                  MainModel.edit_text,
                  initial_value='Enter text here...')

I solved it by adding these lines in _inflate():

        cls = getter_descriptor.__self__
        getter_descriptor_ = cls.__getattribute__(cls, getter_descriptor.__name__)
        setter_descriptor_ = cls.__getattribute__(cls, setter_descriptor.__name__)
        return (
            getter_descriptor_.__get__(widget),
            setter_descriptor_.__get__(widget),
            widget.__getattribute__(signal_name) if signal_name is not None else None
        )

Should I correct two_way() like your comment on one_way()?
Thank you!

**Comment by tom-a-horrocks** [comment]
Hmm, the original lines of code work when I run them on the example, both in pyside2 and pyside6. If you want to post/link your project I can take a look, otherwise I'm out of ideas!
